"""place_footprints.py - deterministic footprint placement + net assignment
for sh03-controller.kicad_pcb.

Run with KiCad's bundled interpreter (not system python):
  python3 scripts/place_footprints.py

Idempotent and regenerating: every run wipes all footprints EXCEPT the
mounting holes (H1-H4 -- stored as ordinary FOOTPRINT objects in the board
file, not board-graphic holes; preserved verbatim, never touched) and
rebuilds every other footprint from build/sh03.net. Export the netlist
first:
  kicad-cli sch export netlist --format kicadsexpr -o build/sh03.net sh03-controller.kicad_sch

Determinism: pcbnew mints a random UUID for every object it constructs
(FootprintLoad(), and every field/graphic/pad that comes along with it).
Loaded from a saved-and-reopened board, pcbnew's footprint container order
is itself a function of those UUID values (verified empirically -- two
placement runs that differ only in UUID text produce different
board.GetFootprints() order after LoadBoard(), which reorders the pads
route_board.py feeds into its MST/routing decisions). Every UUID this
script mints is therefore overwritten with a UUID5 derived from a fixed
namespace and a stable content key (refdes, field name, pad number, graphic
index), so re-running against the same netlist regenerates the exact same
bytes.
"""

import os
import re
import sys
import uuid

import pcbnew

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PCB_PATH = os.path.join(PROJECT_DIR, "sh03-controller.kicad_pcb")
NET_PATH = os.path.join(PROJECT_DIR, "build", "sh03.net")
PROJECT_FP_LIB_TABLE = os.path.join(PROJECT_DIR, "fp-lib-table")


def _default_global_fp_lib_table():
    """Path to KiCad's own (not this project's) global fp-lib-table --
    listing every standard KiCad footprint library (Resistor_SMD,
    Capacitor_SMD, Connector_JST, TestPoint, ...). This used to be a single
    hardcoded Windows desktop path; on any other OS (this pipeline is
    designed to run inside kicad/kicad:10.0 via Docker) os.environ.get(
    "APPDATA", <that Windows path>) still
    resolved to the Windows literal (POSIX has no APPDATA), so
    load_fp_lib_table() silently found nothing there and only the
    project's OWN fp-lib-table (1 entry) ever got merged in. Every
    standard-library FPID (R_0805, C_0805, JST_XH, TestPoint_THTPad, ...)
    then failed to resolve, and place_footprints.py silently placed only
    the handful of refs whose footprint happened to live in the project's
    own library -- 3, on this board -- instead of raising loudly. Fixed by
    branching on os.name so both environments resolve correctly; the
    KICAD10_GLOBAL_FP_LIB_TABLE override still wins over either default."""
    override = os.environ.get("KICAD10_GLOBAL_FP_LIB_TABLE")
    if override:
        return override
    if os.name == "nt":
        appdata = os.environ.get(
            "APPDATA", os.path.join(os.path.expanduser("~"), "AppData", "Roaming")
        )
        return os.path.join(appdata, "kicad", "10.0", "fp-lib-table")
    # kicad/kicad:10.0's Docker image (and a normal Linux install) keeps
    # the global table under the user config dir, XDG-style.
    config_home = os.environ.get("XDG_CONFIG_HOME", os.path.join(os.path.expanduser("~"), ".config"))
    return os.path.join(config_home, "kicad", "10.0", "fp-lib-table")


GLOBAL_FP_LIB_TABLE = _default_global_fp_lib_table()

# Footprints that already exist on the board as ordinary FOOTPRINT objects
# but are not schematic components (mechanical mounting holes). Never
# deleted or regenerated by this script -- preserved however they're stored.
PRESERVED_REFS = {"H1", "H2", "H3", "H4"}

# Fixed namespace for every deterministic UUID this pipeline mints. Same
# value used (independently) in route_board.py and add_ground_pour.py --
# the key strings passed to uuid.uuid5() are already scoped per-script, so
# the namespace itself doesn't need to be shared, only stable.
UUID_NAMESPACE = uuid.UUID("25a1abba-b61d-5666-8453-b2e72c16e5ab")
# Stable namespace for deterministic object identifiers.


def stable_uuid(key):
    return str(uuid.uuid5(UUID_NAMESPACE, key))


def set_uuid(item, key):
    """Overwrite item's KIID in place. m_Uuid is exposed read-only by the
    SWIG binding, but it returns a reference to the live C++ object, and
    KIID.Clone() copies a new value into it -- verified against KiCad
    10.0.5's pcbnew bindings (direct `item.m_Uuid = ...` raises, `.Clone()`
    on the returned reference mutates the real field)."""
    item.m_Uuid.Clone(pcbnew.KIID(stable_uuid(key)))


# ---------------------------------------------------------------------------
# PLACEMENT TABLE -- edit coordinates here for later passes.
# Units: mm (KiCad page coordinates). Rotation: degrees. layer: "front"/"back".
# ---------------------------------------------------------------------------
PLACEMENT = {
    # J1/J2 rotation and slot fixed 2026-08-12c (latch-mirror + stock-board
    # slot-order rework). Two independent bugs, found and fixed together:
    #
    # 1. LATCH/PIN-1 MIRROR (rot 90 -> 270). The board's own pad-report
    #    showed J1 pin 1 (/TH2) landing at the SOUTH end of its span and
    #    pin 14 (/GND) at the NORTH end -- backwards from
    #    the mechanical service description ("pin 1 is the top pin of each
    #    connector, with the GND pins at the bottom", confirmed by continuity
    #    spot-checks on the OEM panel board). Root cause, confirmed empirically against real
    #    pcbnew (not hand-derived): this footprint has only two valid
    #    back-side rotations that keep it "long-axis vertical" -- 90 and
    #    270 -- and for THIS footprint's pad layout they are the only two
    #    reachable pin-1 outcomes (north or south); there is no
    #    combination of Flip() direction and rotation that changes pin-1
    #    north/south placement without also changing it, i.e. no
    #    independent "fix pin-1 only" knob exists at the placement level.
    #    rot=90 (the original, buggy value) put pin 1 south; rot=270 puts
    #    it north. Verified the courtyard bounding box is IDENTICAL
    #    between rot=90 and rot=270 (same footprint, rotated 180 deg
    #    extra, occupies the same rectangular envelope) -- so this is a
    #    zero-clearance-impact rotation-only fix, not a footprint-library
    #    change. Because the whole 3D part (pads + STEP-model latch
    #    geometry) rotates as one rigid body, this same 180 deg fix also
    #    reorients the latch to the correct side -- the two symptoms
    #    (latch facing wrong way, pin-1 on the wrong end) were the same
    #    bug, exactly as predicted before this analysis started.
    #
    # 2. SLOT SWAP (J1<->J2 physical position). User visual ground-truth:
    #    on the stock dryer panel board, the 14-pos connector (our J1,
    #    thermal/air) sits at the BOTTOM and the 15-pos (our J2, vents)
    #    at the TOP. Our board had them backwards (J1 north / J2 south)
    #    since the very first placement commit. The enclosure cavity
    #    coordinate frame is a fixed case feature shared by the stock
    #    board and this replacement (layout-plan.md's cavity-origin
    #    convention, "matching the OEM panel board" framing for pin-1
    #    orientation) -- nothing suggests the replacement sled mounts
    #    rotated relative to the stock board's own orientation, so cavity
    #    "top" = stock-board "top" and the swap is a straight J1<->J2 slot
    #    exchange, not a coordinate re-derivation.
    #
    #    New slot Y positions reuse the EXACT three window gaps from the
    #    pre-fix design (3.125mm top / 2.625mm middle / 2.7mm bottom,
    #    which summed exactly against the 51.2mm window height and were
    #    already fit-checked), just reassigning which connector sits in
    #    which gap-bounded slot -- confirmed empirically (not by hand
    #    algebra) that courtyard bboxes for both connectors are
    #    numerically near-identical to the pre-fix H1/H3 clearance
    #    figures (docs/layout-plan.md "Settled: H1<->J1 and H3<->J2
    #    clearance... 2.205mm" -- same order of magnitude confirmed for
    #    the new H1<->J2 / H3<->J1 pairing). X is unchanged at 47.4mm for
    #    both (courtyard X-span doesn't move between rot 90/270, see
    #    above).
    "J2":  (47.4, 49.625, 270, "back"),   # north slot (was J1's slot)
    "J1":  (47.4, 73.625, 270, "back"),   # south slot (was J2's slot)
    "U1":  (95.0, 61.1, 90, "front"),
    # R1-R4 relocated off the X=58 column entirely (2026-08-11, structural
    # fix after router-side mitigations -- PRIORITY_NETS net ordering, a
    # wider RIPUP_MARGIN_MM, a multi-target A* start, and a small explicit
    # stub-unlock set, tried in that order in route_board.py -- proved
    # insufficient or unstable; see route_board.py's PRIORITY_NETS and
    # STUB_UNLOCK_NETS comments for that whole investigation). Each
    # resistor now sits immediately next to the specific U1 pin its
    # signal-side edge actually targets, so that edge is a trivial local
    # hop instead of a long run through the J1/J2-escape-stub-choked
    # corridor between X=58 and U1. This is also just the electrically
    # sane home for pull resistors -- next to the node they're pulling,
    # not stranded across the board -- independent of the routing win.
    #
    # Targets read off the live board's actual pad positions/nets (not
    # assumed from the schematic), since two of the four don't sit where a
    # first guess would put them:
    #   R1 pin2 (/TH2) -> U1 pin 26 (75.95, 49.67) -- NORTH row, west end.
    #     Open space is the former TP1-14 strip, north of U1's own
    #     courtyard (top edge y=48.105) -- not south of anything.
    #   R2 pin2 (/TH1) -> U1 pin 27 (78.49, 49.67) -- north row, same strip.
    #   R3 pin1 (/MC_HOT2) -> U1 pin 17 (108.97, 72.53) -- SOUTH row, near
    #     the EAST end (not the antenna/west end R1/R2 are near), in the
    #     former TP15-29 pocket.
    #   R4 pin1 (/MC_HOT1) -> U1 pin 18 (111.51, 72.53) -- south row, same
    #     pocket, next to R3.
    # R1/R2 pin1 (/+3V3) and R3/R4 pin2 (/GND) are the OTHER end of each
    # part and don't drive placement -- /+3V3 still crosses the board to
    # reach U1.1/U1.2, but with two of the three previously-contested nets
    # no longer touching that corridor at all, it has far less competing
    # traffic. /GND isn't track-routed (add_ground_pour.py's zone + this
    # script's existing single-layer-pad stitching-via logic in
    # route_board.py picks up R3/R4's SMD GND pad automatically -- no
    # manual stub needed).
    #
    # X = the target pin's own X (direct alignment, not an offset).
    # Y: R1/R2 at 43.0 -- courtyard (1.99mm wide x 3.45mm tall at rot 270)
    #   spans Y[41.275, 44.725], 3.38mm clear of U1's courtyard top edge
    #   (48.105), body clear of H1/H2/J1/J2 by tens of mm. R3/R4 at 78.0 --
    #   courtyard spans Y[76.275, 79.725], 6.245mm clear of the antenna
    #   keepout's south edge (70.03 -- confirmed clear, not adjacent to it)
    #   and clear of C2's courtyard (113.255-116.745, 79.025mm max) by
    #   0.75mm on the R4 side. J3's courtyard (51.505-64.995, 75.455-
    #   88.055) and H3/H4 are tens of mm away on both pairs -- no overlap.
    # Rotation 270 for all four: this footprint's pin 1 sits at local
    # x=-0.9125 relative to its own center (pin 2 at +0.9125, confirmed by
    # reading R1's actual pad positions off the board pre-move) -- at 270
    # deg that puts pin 1 due north and pin 2 due south of the part's
    # center. R1/R2's target pin is their OWN pin 2 (south-facing, correct
    # since the north-row target sits south of R1/R2's new position in the
    # open strip further north). R3/R4's target is their pin 1
    # (north-facing, correct since their south-row target sits north of
    # R3/R4's new position in the pocket further south). Same rotation
    # value, opposite pins, because the two pairs approach their targets
    # from opposite sides -- verified against the live pad data, not
    # assumed symmetric.
    # Moved front->back 2026-08-12 so every SMD part on the board sits on
    # B.Cu -- single-side (back) JLCPCB Economic PCBA can then machine-place
    # the whole population, leaving the builder (who isn't comfortable
    # hand-soldering SMD) with THT only (J3, U1's two header strips).
    # X/Y/rotation are UNCHANGED from the prior front-side values -- verified
    # empirically (not assumed) against KiCad 10.0.5's actual Flip()
    # semantics: for a symmetric 2-pad SMD footprint, FOOTPRINT.SetPosition()
    # then FOOTPRINT.Flip(pos, FLIP_DIRECTION_LEFT_RIGHT) then
    # FOOTPRINT.SetOrientationDegrees(rot) with the SAME rot value used on
    # the front reproduces byte-identical absolute pad X/Y for every pad
    # number, just on B.Cu instead of F.Cu (probed directly via pcbnew: R at
    # rot=270, C at rot=0, both reproduce their prior front-side pad map
    # exactly). That means every geometric fact the front-side comments
    # below already establish -- R1/R2/R3/R4's pin1/pin2 north/south facing,
    # the courtyard clearances, the antenna-keepout margin -- still holds
    # unchanged on the back; only the copper/silkscreen layer changed. The
    # alignment this placement depends on (R1.2/R2.2 under U1.26/27, R3.1/
    # R4.1 under U1.17/18) is asserted numerically at the end of main(),
    # against live pad positions, not just trusted from this comment.
    "R1":  (75.95, 43.0, 270, "back"),
    "R2":  (78.49, 43.0, 270, "back"),
    "R3":  (108.97, 78.0, 270, "back"),
    "R4":  (111.51, 78.0, 270, "back"),
    "C1":  (117.0, 42.0, 0, "back"),
    "C3":  (110.0, 42.0, 0, "back"),
    "C2":  (115.0, 78.0, 0, "back"),
    # J3: relocated bottom-left-of-center, rotated 180 deg so its mating
    # opening faces -Y / north, toward the top board edge (was +X at rot
    # 90) -- see docs/layout-plan.md and scripts/place_footprints.py's git
    # history for the rot->opening-direction verification. Courtyard
    # clears U1 (top) and J2's courtyard; both gaps verified post-build via
    # check_placement.py.
    "J3":  (62.0, 85.2, 180, "front"),
}
FALLBACK_XY = (40.0, 95.0)  # off-board parking spot for refs missing above

# R1-R4 reference-label positions -- see the "elif ref in R_REF_LABEL_XY"
# branch in main() for why these are pinned explicitly. X matches each
# part's own PLACEMENT X (so the label sits directly over/under its own
# part, not drifting toward its neighbour); Y is 1mm clear of the pair's
# shared courtyard edge, on the side away from the row it's routing
# toward (R1/R2 label north, above the row; R3/R4 label south, below it).
R_REF_LABEL_XY = {
    "R1": (75.95, 40.3),
    "R2": (78.49, 40.3),
    "R3": (108.97, 80.4),
    "R4": (111.51, 80.4),
}


def expand_vars(uri, project_dir):
    footprints_dir = os.environ.get("KICAD10_FOOTPRINT_DIR")
    if not footprints_dir:
        if os.name == "nt":
            # python.exe lives at .../KiCad/10.0/bin/python.exe
            kicad_root = os.path.dirname(os.path.dirname(sys.executable))
            footprints_dir = os.path.join(kicad_root, "share", "kicad", "footprints")
        else:
            # system python3 lives at /usr/bin/python3 -- dirname/dirname
            # of that is "/", not a KiCad install root, so the same
            # Windows-shaped derivation silently produced "/share/kicad/
            # footprints" (missing "usr") on kicad/kicad:10.0's Docker
            # image / a normal Linux package install. Use the real
            # system-wide path directly instead of deriving it.
            footprints_dir = "/usr/share/kicad/footprints"
    uri = uri.replace("${KIPRJMOD}", project_dir)
    uri = uri.replace("${KICAD10_FOOTPRINT_DIR}", footprints_dir)
    uri = re.sub(r"\$\{([A-Za-z0-9_]+)\}", lambda m: os.environ.get(m.group(1), m.group(0)), uri)
    return uri.replace("/", os.sep)


def load_fp_lib_table(path, project_dir, seen=None):
    """Parse an fp-lib-table, returning {nickname: resolved_dir}.
    Recursively follows nested `type "Table"` entries -- KiCad's global
    table on this machine is one indirection layer around the shipped
    default library list."""
    libs = {}
    if seen is None:
        seen = set()
    path = os.path.abspath(path)
    if path in seen or not os.path.isfile(path):
        return libs
    seen.add(path)
    text = open(path, encoding="utf-8").read()
    for m in re.finditer(
        r'\(lib\s*\(name "([^"]*)"\)\s*\(type "([^"]*)"\)\s*\(uri "([^"]*)"\)', text
    ):
        name, typ, uri_ = m.groups()
        resolved = expand_vars(uri_, project_dir)
        if typ == "Table":
            libs.update(load_fp_lib_table(resolved, project_dir, seen))
        else:
            libs[name] = resolved
    return libs


def parse_netlist(path):
    """Returns (components, nets).
    components: {ref: {"value": str, "footprint": str or None}}
    nets: [{"name": str, "nodes": [(ref, pin), ...]}]
    """
    text = open(path, encoding="utf-8").read().replace("\r\n", "\n")

    components = {}
    for part in re.split(r"\n\t\t\(comp\n", text)[1:]:
        end = re.search(r"\n\t\t\)\n", part)
        block = part[: end.start()] if end else part
        ref_m = re.search(r'\(ref "([^"]+)"\)', block)
        val_m = re.search(r'\(value "([^"]*)"\)', block)
        fp_m = re.search(r'\(footprint "([^"]*)"\)', block)
        if not ref_m:
            continue
        components[ref_m.group(1)] = {
            "value": val_m.group(1) if val_m else "",
            "footprint": fp_m.group(1) if fp_m else None,
        }

    nets = []
    for part in re.split(r"\n\t\t\(net\n", text)[1:]:
        end = re.search(r"\n\t\t\)\n", part)
        block = part[: end.start()] if end else part
        name_m = re.search(r'\(name "([^"]*)"\)', block)
        nodes = re.findall(
            r'\(node\n\t\t\t\t\(ref "([^"]+)"\)\n\t\t\t\t\(pin "([^"]+)"\)', block
        )
        nets.append({"name": name_m.group(1) if name_m else "", "nodes": nodes})

    return components, nets


def main():
    if not os.path.isfile(NET_PATH):
        sys.exit(f"netlist not found: {NET_PATH} -- export it first (see module docstring)")

    components, nets = parse_netlist(NET_PATH)

    fp_libs = {}
    fp_libs.update(load_fp_lib_table(GLOBAL_FP_LIB_TABLE, PROJECT_DIR))
    fp_libs.update(load_fp_lib_table(PROJECT_FP_LIB_TABLE, PROJECT_DIR))  # project overrides global
    print(f"[place] resolved {len(fp_libs)} footprint librar(y/ies) from fp-lib-table")

    board = pcbnew.LoadBoard(PCB_PATH)

    # --- wipe all footprints except the preserved mounting holes ---
    # NOTE: KiCad 10.0.5's pcbnew python bindings corrupt PCB_IO_MGR's cached
    # plugin instance if a removed FOOTPRINT's SWIG proxy is garbage
    # collected (refcount -> 0) *before* all subsequent FootprintLoad() calls
    # are done -- FootprintLoad() then raises
    # "AttributeError: 'SwigPyObject' object has no attribute 'FootprintLoad'".
    # Reproduced deterministically; keeping every removed proxy alive in a
    # list for the script's lifetime avoids it (verified: 20/20 loads
    # succeed with this held vs. failing on the very first load without it).
    _removed_kept_alive = []
    removed = 0
    preserved_refdes_fixed = 0
    for fp in list(board.GetFootprints()):
        if fp.GetReference() in PRESERVED_REFS:
            # H1-H4 are never deleted/regenerated (see PRESERVED_REFS above),
            # but their Reference text's LAYER is normalized here on every
            # run so the silkscreen-refdes convention can't drift back via a
            # stray hand-edit of the board file: mounting-hole references are
            # documentation for assembly/fab, not something printed on the
            # physical silkscreen, so they belong on *.Fab (visible there),
            # never on *.SilkS. Only the layer is touched -- position, text
            # size and visibility are left as already saved on the board.
            ref_field = fp.Reference()
            target_layer = pcbnew.B_Fab if fp.IsFlipped() else pcbnew.F_Fab
            if ref_field.GetLayer() != target_layer:
                ref_field.SetLayer(target_layer)
                preserved_refdes_fixed += 1
            continue
        board.Remove(fp)
        _removed_kept_alive.append(fp)
        removed += 1
    print(f"[place] removed {removed} existing footprint(s) (kept {sorted(PRESERVED_REFS)})")
    if preserved_refdes_fixed:
        print(f"[place] moved {preserved_refdes_fixed} preserved ref(s) Reference text "
              f"off silkscreen onto *.Fab")

    unresolved_fpids = []
    empty_footprint_refs = []
    unplaced_refs = []          # refs not in PLACEMENT table -> parked off-board
    net_objs = {}                # net name -> NETINFO_ITEM (reused across runs by name)
    placed_footprints = {}       # ref -> FOOTPRINT

    for ref in sorted(components):
        comp = components[ref]
        fpid = comp["footprint"]
        if not fpid:
            empty_footprint_refs.append(ref)
            continue

        if ":" not in fpid:
            unresolved_fpids.append((ref, fpid, "no library nickname in FPID"))
            continue
        libname, fpname = fpid.split(":", 1)
        libdir = fp_libs.get(libname)
        if not libdir:
            unresolved_fpids.append((ref, fpid, f"library nickname '{libname}' not in fp-lib-table"))
            continue

        fp = pcbnew.FootprintLoad(libdir, fpname)
        if fp is None:
            unresolved_fpids.append((ref, fpid, f"FootprintLoad returned None from {libdir}"))
            continue

        fp.SetReference(ref)
        fp.SetValue(comp["value"])
        board.Add(fp)

        # Deterministic UUIDs: the footprint itself, its fields (Reference,
        # Value, Datasheet, Description, ...), every graphical item (silk
        # rects/polys/text -- keyed by position in the library's fixed,
        # file-order iteration since they have no other stable identity),
        # and every pad (keyed by pad number, which is stable and unique
        # within a footprint).
        set_uuid(fp, f"sh03:{ref}:footprint")
        for field in fp.GetFields():
            set_uuid(field, f"sh03:{ref}:field:{field.GetName()}")
        for idx, item in enumerate(fp.GraphicalItems()):
            set_uuid(item, f"sh03:{ref}:graphic:{idx}")
        for pad in fp.Pads():
            set_uuid(pad, f"sh03:{ref}:pad:{pad.GetNumber()}")

        if ref in PLACEMENT:
            x, y, rot, layer = PLACEMENT[ref]
        else:
            x, y = FALLBACK_XY
            rot, layer = 0, "front"
            unplaced_refs.append(ref)

        pos = pcbnew.VECTOR2I(pcbnew.FromMM(x), pcbnew.FromMM(y))
        fp.SetPosition(pos)
        if layer == "back":
            fp.Flip(pos, pcbnew.FLIP_DIRECTION_LEFT_RIGHT)
        fp.SetOrientationDegrees(rot)

        if ref == "J3":
            # J3's library-default Reference text rides along with its
            # rot-180 placement and lands overhanging the board's bottom
            # edge (DRC silk_edge_clearance). Pin it to a fixed spot clear
            # of J3's own courtyard (north of its top edge, y~75.455),
            # U1's courtyard (west of x~66.6) and J2's courtyard (east of
            # x~50.7) -- set explicitly every run so the placement stays
            # deterministic regardless of rotation.
            ref_field = fp.Reference()
            ref_field.SetVisible(True)
            ref_field.SetLayer(pcbnew.F_SilkS)
            ref_field.SetTextSize(pcbnew.VECTOR2I(pcbnew.FromMM(1.0), pcbnew.FromMM(1.0)))
            ref_field.SetTextThickness(pcbnew.FromMM(0.15))
            ref_field.SetTextAngle(pcbnew.EDA_ANGLE(0, pcbnew.DEGREES_T))
            ref_field.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(62.0), pcbnew.FromMM(74.3)))

        elif ref in R_REF_LABEL_XY:
            # R1-R4's library-default Reference text rides along with
            # their rot-270 placement (see PLACEMENT's comment for the
            # relocation rationale) and at 2.54mm pitch lands overlapping
            # the NEIGHBOURING resistor's silkscreen/pads -- caught by a
            # real DRC run (silk_overlap + silk_over_copper, 7 warnings
            # over the baseline). Pin each one to a fixed spot clear of
            # both parts in the pair and of the courtyard behind them
            # (north of R1/R2's row for the north pair, south of R3/R4's
            # for the south pair), same fixed-every-run approach as J3.
            #
            # Layer/mirror MUST track the part's actual side (back, since
            # the 2026-08-12 all-SMD-on-back move) -- this used to
            # unconditionally force F_SilkS regardless of `layer`, which was
            # harmless while every ref in this branch was front-side but
            # would have silently left R1-R4's silkscreen refdes on the
            # FRONT while the parts themselves moved to the back. Set
            # explicitly every run, same deterministic-override rationale
            # as TextSize/TextThickness/TextAngle below, not left to
            # whatever fp.Flip() happened to set earlier in this loop.
            x, label_y = R_REF_LABEL_XY[ref]
            ref_field = fp.Reference()
            ref_field.SetVisible(True)
            ref_field.SetLayer(pcbnew.B_SilkS if layer == "back" else pcbnew.F_SilkS)
            ref_field.SetMirrored(layer == "back")
            ref_field.SetTextSize(pcbnew.VECTOR2I(pcbnew.FromMM(1.0), pcbnew.FromMM(1.0)))
            ref_field.SetTextThickness(pcbnew.FromMM(0.15))
            ref_field.SetTextAngle(pcbnew.EDA_ANGLE(0, pcbnew.DEGREES_T))
            ref_field.SetPosition(pcbnew.VECTOR2I(pcbnew.FromMM(x), pcbnew.FromMM(label_y)))

        placed_footprints[ref] = fp

    if empty_footprint_refs:
        print(f"[place] refs with empty footprint field, skipped: {empty_footprint_refs}")
    if unresolved_fpids:
        print("[place] UNRESOLVED FPIDs:")
        for ref, fpid, reason in unresolved_fpids:
            print(f"  {ref}: {fpid} -- {reason}")
    if unplaced_refs:
        print(f"[place] refs missing from PLACEMENT table, parked at {FALLBACK_XY}: {unplaced_refs}")

    # --- net assignment ---
    unmatched_pads = []  # netlist pin refs with no matching pad, or no footprint at all
    for net in nets:
        name = net["name"]
        if not name:
            continue
        for ref, pin in net["nodes"]:
            fp = placed_footprints.get(ref)
            if fp is None:
                unmatched_pads.append((ref, pin, name, "no footprint placed for this ref"))
                continue
            pad = None
            for candidate in fp.Pads():
                if candidate.GetNumber() == pin:
                    pad = candidate
                    break
            if pad is None:
                unmatched_pads.append((ref, pin, name, "pad not found on footprint"))
                continue

            ni = net_objs.get(name)
            if ni is None:
                ni = board.FindNet(name)  # reuse a net already on the board, if any
                if ni is None:
                    ni = pcbnew.NETINFO_ITEM(board, name)
                    board.Add(ni)
                net_objs[name] = ni
            pad.SetNet(ni)

    if unmatched_pads:
        print("[place] UNMATCHED pad/pin references:")
        for ref, pin, name, reason in unmatched_pads:
            print(f"  {ref} pin {pin} (net {name}): {reason}")

    # --- R/U1 escape-stub X-alignment, asserted numerically ---
    #
    # PRE_ROUTES in route_board.py depends on R1.2/R2.2 (2026-08-12: R3.1/
    # R4.1 too, once R3/R4 join the pre-route scheme's alignment
    # requirement even though they aren't PRE_ROUTES entries themselves)
    # sitting X-aligned with their target U1 pin, since that's what turns
    # each hop into a trivial straight track instead of a router search.
    # The front->back move claims (in PLACEMENT's comment) that X is
    # unchanged by the flip -- checked here against LIVE pad positions
    # instead of just trusted, so a future PLACEMENT edit that breaks the
    # alignment fails loudly here rather than surfacing as a cryptic
    # PRE_ROUTES SystemExit three pipeline stages later.
    ALIGNMENT_CHECKS = [
        ("R1", "2", "U1", "26"),
        ("R2", "2", "U1", "27"),
        ("R3", "1", "U1", "17"),
        ("R4", "1", "U1", "18"),
    ]

    def _pad_pos_mm(ref, pin):
        fp = placed_footprints.get(ref)
        if fp is None:
            return None
        for pad in fp.Pads():
            if pad.GetNumber() == pin:
                p = pad.GetPosition()
                return (pcbnew.ToMM(p.x), pcbnew.ToMM(p.y))
        return None

    alignment_failures = []
    for from_ref, from_pin, to_ref, to_pin in ALIGNMENT_CHECKS:
        a = _pad_pos_mm(from_ref, from_pin)
        b = _pad_pos_mm(to_ref, to_pin)
        if a is None or b is None:
            alignment_failures.append(
                f"{from_ref}.{from_pin}->{to_ref}.{to_pin}: pad not found "
                f"(a={a}, b={b})")
            continue
        dx = abs(a[0] - b[0])
        print(f"[place] alignment check {from_ref}.{from_pin} (x={a[0]:.4f}) "
              f"vs {to_ref}.{to_pin} (x={b[0]:.4f}): dx={dx:.4f}mm")
        if dx >= 0.05:
            alignment_failures.append(
                f"{from_ref}.{from_pin}->{to_ref}.{to_pin}: X misaligned by "
                f"{dx:.4f}mm (>=0.05mm)")

    if alignment_failures:
        raise SystemExit(
            "[place] FAILED: R/U1 escape-stub X-alignment broken:\n  " +
            "\n  ".join(alignment_failures))

    board.Save(PCB_PATH)
    print(f"[place] saved {PCB_PATH}")
    print(f"[place] placed {len(placed_footprints)} footprint(s), {len(net_objs)} net(s) touched")

    # Fail loudly instead of silently saving a mostly-empty board: this
    # used to only print "UNRESOLVED FPIDs" above and continue, so a
    # broken footprint-library path (see GLOBAL_FP_LIB_TABLE's docstring)
    # silently produced a 3-footprint board with a 0 exit code, and every
    # downstream stage (route_board.py et al.) "succeeded" against that
    # garbage without complaint.
    if unresolved_fpids:
        raise SystemExit(
            f"[place] FAILED: {len(unresolved_fpids)} FPID(s) could not be resolved "
            f"(see UNRESOLVED FPIDs above) -- the saved board is missing those "
            f"footprints entirely. Check GLOBAL_FP_LIB_TABLE / KICAD10_FOOTPRINT_DIR."
        )


if __name__ == "__main__":
    main()
